import AppKit

private enum CharState {
    case idle
    case walkLeft
    case walkRight
}

final class CharacterController {

    // visual
    private let targetHeight: CGFloat = 200
    private let dockOffset: CGFloat = 8

    // motion — slow stroll: ~one footstep per second, 18 px/s
    private let walkSpeedPxPerSec: CGFloat = 18
    private let movementInterval: TimeInterval = 1.0 / 30.0

    // animation timing — slower transitions for a calm walk
    private let idleFrameInterval: TimeInterval = 0.30
    private let walkFrameInterval: TimeInterval = 0.45

    // deterministic phase pattern: idle 3s -> left 3s -> right 3s -> repeat
    private let phaseDuration: TimeInterval = 3.0
    private let phaseSequence: [CharState] = [.idle, .walkLeft, .walkRight]

    // no Y bounce — pure horizontal translation feels like walking, not floating
    private let walkBobAmplitude: CGFloat = 0

    private let sprites: Sprites
    private let window: CharacterWindow
    private let displaySize: NSSize

    private var state: CharState = .idle
    private var phaseIndex: Int = 0

    // frame cycles per state
    //   idle: ping-pong 0->1->2->1 for natural breath
    //   walk: full ping-pong 0->1->2->1. Walk-left frames are now generated by
    //         horizontally flipping walk-right at load time (Sprites.swift),
    //         so the row is internally consistent and the wobble is gone.
    private var pingPongStep: Int = 0
    private let idleOrder: [Int] = [0, 1, 2, 1]
    private let walkOrder: [Int] = [0, 1, 2, 1]

    private var frameTimer: Timer?
    private var moveTimer: Timer?
    private var phaseTimer: Timer?

    private(set) var enabled: Bool = false

    init(sprites: Sprites) {
        self.sprites = sprites
        let raw = sprites.frameSize
        let aspect = raw.width / max(raw.height, 1)
        self.displaySize = NSSize(
            width: floor(targetHeight * aspect),
            height: targetHeight
        )
        self.window = CharacterWindow(frameSize: displaySize)
        positionAtStart()
        applyCurrentFrame()
    }

    // MARK: - public

    func setEnabled(_ on: Bool) {
        guard on != enabled else { return }
        enabled = on
        if on {
            window.orderFront(nil)
            startTimers()
        } else {
            stopTimers()
            window.orderOut(nil)
        }
    }

    // MARK: - layout

    private func screenFrame() -> NSRect {
        NSScreen.main?.visibleFrame ?? NSRect(x: 0, y: 0, width: 1440, height: 900)
    }

    private func positionAtStart() {
        let scr = screenFrame()
        let x = scr.midX - displaySize.width / 2
        let y = scr.minY + dockOffset
        window.setFrame(NSRect(origin: NSPoint(x: x, y: y), size: displaySize),
                        display: false)
    }

    // MARK: - timers

    private func startTimers() {
        phaseIndex = 0
        pingPongStep = 0
        state = phaseSequence[0]
        applyCurrentFrame()
        scheduleFrameTimer()
        scheduleMoveTimer()
        schedulePhaseTimer()
    }

    private func stopTimers() {
        frameTimer?.invalidate(); frameTimer = nil
        moveTimer?.invalidate(); moveTimer = nil
        phaseTimer?.invalidate(); phaseTimer = nil
    }

    private func scheduleFrameTimer() {
        frameTimer?.invalidate()
        let interval = (state == .idle) ? idleFrameInterval : walkFrameInterval
        let t = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            self?.tickFrame()
        }
        RunLoop.main.add(t, forMode: .common)
        frameTimer = t
    }

    private func scheduleMoveTimer() {
        let t = Timer.scheduledTimer(withTimeInterval: movementInterval, repeats: true) { [weak self] _ in
            self?.tickMove()
        }
        RunLoop.main.add(t, forMode: .common)
        moveTimer = t
    }

    private func schedulePhaseTimer() {
        phaseTimer?.invalidate()
        let t = Timer.scheduledTimer(withTimeInterval: phaseDuration, repeats: true) { [weak self] _ in
            self?.advancePhase()
        }
        RunLoop.main.add(t, forMode: .common)
        phaseTimer = t
    }

    // MARK: - ticks

    private func tickFrame() {
        let order = currentOrder
        pingPongStep = (pingPongStep + 1) % order.count
        applyCurrentFrame()
    }

    private var currentOrder: [Int] {
        state == .idle ? idleOrder : walkOrder
    }

    private var currentFrameIndex: Int {
        let order = currentOrder
        return order[pingPongStep % order.count]
    }

    private func applyCurrentFrame() {
        let frames: [NSImage]
        switch state {
        case .idle: frames = sprites.idle
        case .walkRight: frames = sprites.walkRight
        case .walkLeft: frames = sprites.walkLeft
        }
        guard !frames.isEmpty else { return }
        window.imageView.image = frames[currentFrameIndex % frames.count]
    }

    private func tickMove() {
        let scr = screenFrame()
        let baseY = scr.minY + dockOffset

        // walking: advance x, bounce off edges by swapping direction
        if state != .idle {
            let dx = walkSpeedPxPerSec * CGFloat(movementInterval)
            var origin = window.frame.origin
            switch state {
            case .walkLeft:
                origin.x -= dx
                if origin.x <= scr.minX {
                    origin.x = scr.minX
                    state = .walkRight
                    pingPongStep = 0
                    scheduleFrameTimer()
                }
            case .walkRight:
                origin.x += dx
                if origin.x + displaySize.width >= scr.maxX {
                    origin.x = scr.maxX - displaySize.width
                    state = .walkLeft
                    pingPongStep = 0
                    scheduleFrameTimer()
                }
            case .idle:
                break
            }
            // bob up on passing frame (legs together pose); down on stride frames
            let bob = (currentFrameIndex == 1) ? walkBobAmplitude : 0
            origin.y = baseY + bob
            window.setFrameOrigin(origin)
        } else {
            // idle: keep firmly on the floor
            var origin = window.frame.origin
            if origin.y != baseY {
                origin.y = baseY
                window.setFrameOrigin(origin)
            }
        }
    }

    private func advancePhase() {
        phaseIndex = (phaseIndex + 1) % phaseSequence.count
        let next = phaseSequence[phaseIndex]
        guard next != state else { return }
        state = next
        pingPongStep = 0
        applyCurrentFrame()
        scheduleFrameTimer()
    }
}
